#!/usr/bin/env python3
"""ops/plot_equity_overlay.py -- Overlay equity curves from multiple backtest runs.

Usage:
    python ops/plot_equity_overlay.py run_id1 run_id2 ...
    python ops/plot_equity_overlay.py --latest 5
    python ops/plot_equity_overlay.py --latest 5 --min-trades 20
"""
import csv
import json
import os
import sys
import webbrowser
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
LOGS = REPO / "ops" / "logs"
MAX_POINTS = 2000  # downsample for browser performance

COLORS = [
    "#4fc3f7", "#81c784", "#ffb74d", "#e57373", "#ba68c8",
    "#4dd0e1", "#aed581", "#ff8a65", "#f06292", "#7986cb",
]


def find_equity_file(run_id: str) -> Path | None:
    """Find equity CSV by run_id (supports partial match)."""
    for pattern in [f"equity_{run_id}.csv", f"equity_bt_{run_id}.csv"]:
        p = LOGS / pattern
        if p.exists():
            return p
    # Partial match
    for p in sorted(LOGS.glob(f"equity_*{run_id}*.csv")):
        return p
    return None


def find_latest(n: int, min_trades: int = 0) -> list[str]:
    """Find N most recent completed runs."""
    summaries = sorted(LOGS.glob("bt_summary_bt_*.json"), key=os.path.getmtime)
    summaries = [s for s in summaries if "latest" not in s.name]
    if min_trades > 0:
        filtered = []
        for s in summaries:
            try:
                with open(s) as f:
                    d = json.load(f)
                if int(d.get("trades_closed", 0) or 0) >= min_trades:
                    filtered.append(s)
            except Exception:
                continue
        summaries = filtered
    return [s.stem.replace("bt_summary_", "") for s in summaries[-n:]]


def get_label(run_id: str) -> str:
    """Build label from run_header and summary."""
    # Try run_header for label
    for p in LOGS.glob(f"run_header_*{run_id}*.json"):
        try:
            with open(p) as f:
                hdr = json.load(f)
            if hdr.get("label"):
                return hdr["label"]
        except Exception:
            pass
    # Try summary for stats
    for p in LOGS.glob(f"bt_summary_*{run_id}*.json"):
        try:
            with open(p) as f:
                d = json.load(f)
            pnl = d.get("pnl_usd", "?")
            wr = d.get("win_rate_pct", "?")
            trades = d.get("trades_closed", "?")
            return f"{run_id[-8:]} PnL=${pnl} WR={wr}% t={trades}"
        except Exception:
            pass
    return run_id[-12:]


def load_equity(path: Path) -> list[dict]:
    """Load equity CSV and downsample."""
    rows = []
    with open(path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                rows.append({
                    "epoch": int(row["epoch"]),
                    "equity": float(row["equity_usd"]),
                })
            except (ValueError, KeyError):
                continue
    # Downsample if too many points
    if len(rows) > MAX_POINTS:
        step = len(rows) / MAX_POINTS
        sampled = []
        for i in range(MAX_POINTS):
            sampled.append(rows[int(i * step)])
        # Always include last point
        sampled.append(rows[-1])
        return sampled
    return rows


def generate_html(datasets: list[dict]) -> str:
    """Generate Chart.js HTML with overlaid equity curves."""
    chart_datasets = []
    for i, ds in enumerate(datasets):
        color = COLORS[i % len(COLORS)]
        points = [{"x": r["epoch"] * 1000, "y": round(r["equity"], 4)} for r in ds["data"]]
        chart_datasets.append({
            "label": ds["label"],
            "data": points,
            "borderColor": color,
            "backgroundColor": "transparent",
            "borderWidth": 1.5,
            "pointRadius": 0,
            "tension": 0.1,
        })

    datasets_json = json.dumps(chart_datasets)

    return f"""<!DOCTYPE html>
<html>
<head>
<title>Argus Equity Overlay</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3"></script>
<style>
body {{ background: #1a1a2e; color: #eee; font-family: monospace; margin: 20px; }}
h1 {{ color: #4fc3f7; font-size: 18px; }}
canvas {{ background: #16213e; border-radius: 8px; }}
.info {{ color: #888; font-size: 12px; margin-top: 10px; }}
</style>
</head>
<body>
<h1>Argus Equity Curve Overlay ({len(datasets)} runs)</h1>
<canvas id="chart" width="1200" height="500"></canvas>
<div class="info">Generated by ops/plot_equity_overlay.py</div>
<script>
new Chart(document.getElementById('chart'), {{
    type: 'line',
    data: {{ datasets: {datasets_json} }},
    options: {{
        responsive: true,
        scales: {{
            x: {{
                type: 'time',
                time: {{ unit: 'day' }},
                ticks: {{ color: '#888' }},
                grid: {{ color: '#333' }}
            }},
            y: {{
                title: {{ display: true, text: 'Equity (USD)', color: '#888' }},
                ticks: {{ color: '#888' }},
                grid: {{ color: '#333' }}
            }}
        }},
        plugins: {{
            legend: {{ labels: {{ color: '#ccc', font: {{ family: 'monospace' }} }} }}
        }}
    }}
}});
</script>
</body>
</html>"""


def main():
    args = sys.argv[1:]
    run_ids = []
    min_trades = 0

    i = 0
    while i < len(args):
        if args[i] == "--latest" and i + 1 < len(args):
            n = int(args[i + 1])
            # Check for --min-trades
            mt = 0
            if i + 3 < len(args) and args[i + 2] == "--min-trades":
                mt = int(args[i + 3])
                i += 2
            run_ids = find_latest(n, mt)
            i += 2
        elif args[i] == "--min-trades" and i + 1 < len(args):
            min_trades = int(args[i + 1])
            i += 2
        else:
            run_ids.append(args[i])
            i += 1

    if not run_ids:
        run_ids = find_latest(5)

    if len(run_ids) < 1:
        print("No runs found.", file=sys.stderr)
        sys.exit(1)

    datasets = []
    for rid in run_ids:
        eq_file = find_equity_file(rid)
        if not eq_file:
            print(f"  skip {rid}: no equity file", file=sys.stderr)
            continue
        data = load_equity(eq_file)
        if not data:
            print(f"  skip {rid}: empty equity", file=sys.stderr)
            continue
        label = get_label(rid)
        datasets.append({"label": label, "data": data, "run_id": rid})
        print(f"  loaded {rid[-12:]}: {len(data)} points, label={label}")

    if not datasets:
        print("No equity data to plot.", file=sys.stderr)
        sys.exit(1)

    html = generate_html(datasets)
    out = LOGS / "equity_overlay.html"
    out.write_text(html, encoding="utf-8")
    print(f"\nOutput: {out}")

    try:
        webbrowser.open(str(out))
    except Exception:
        pass


if __name__ == "__main__":
    main()